; Generated by DelphiLLVMGenerator
declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)

@.fmt_int_nl = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_str_nl = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_read_i = private unnamed_addr constant [3 x i8] c"%d\00"

@g = global i32 0

define i32 @sum3(i32 %arg0, i32 %arg1, i32 %arg2) {
entry:
  %t0 = alloca i32
  store i32 %arg0, ptr %t0
  %t1 = alloca i32
  store i32 %arg1, ptr %t1
  %t2 = alloca i32
  store i32 %arg2, ptr %t2
  %t3 = alloca i32
  store i32 0, ptr %t3
  %t4 = load i32, ptr %t0
  %t5 = load i32, ptr %t1
  %t6 = add i32 %t4, %t5
  %t7 = load i32, ptr %t2
  %t8 = add i32 %t6, %t7
  store i32 %t8, ptr %t3
  %t9 = load i32, ptr %t3
  ret i32 %t9
}

define void @usefor(i32 %arg0) {
entry:
  %t0 = alloca i32
  store i32 %arg0, ptr %t0
  %t1 = alloca i32
  store i32 0, ptr %t1
  %t2 = alloca i32
  store i32 0, ptr %t2
  store i32 0, ptr %t2
  %t3 = load i32, ptr %t0
  store i32 1, ptr %t1
  br label %for_cond_0
for_cond_0:
  %t4 = load i32, ptr %t1
  %t5 = icmp sle i32 %t4, %t3
  br i1 %t5, label %for_body_1, label %for_end_3
for_body_1:
  %t6 = load i32, ptr %t2
  %t7 = load i32, ptr %t1
  %t8 = add i32 %t6, %t7
  store i32 %t8, ptr %t2
  br label %for_step_2
for_step_2:
  %t9 = load i32, ptr %t1
  %t10 = add i32 %t9, 1
  store i32 %t10, ptr %t1
  br label %for_cond_0
for_end_3:
  %t11 = load i32, ptr %t2
  store i32 %t11, ptr @g
  ret void
}

define i32 @main() {
entry:
  store i32 0, ptr @g
  call void @usefor(i32 5)
  %t0 = load i32, ptr @g
  call i32 (ptr, ...) @printf(ptr @.fmt_int_nl, i32 %t0)
  %t1 = load i32, ptr @g
  %t2 = call i32 @sum3(i32 %t1, i32 2, i32 3)
  call i32 (ptr, ...) @printf(ptr @.fmt_int_nl, i32 %t2)
  ret i32 0
}
