; Generated by DelphiLLVMGenerator
declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)

@.fmt_int_nl = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_str_nl = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_read_i = private unnamed_addr constant [3 x i8] c"%d\00"

@v = global i32 0

define i32 @main() {
entry:
  %t0 = alloca i32
  call i32 (ptr, ...) @scanf(ptr @.fmt_read_i, ptr %t0)
  %t1 = load i32, ptr %t0
  store i32 %t1, ptr @v
  %t2 = load i32, ptr @v
  %t3 = add i32 %t2, 10
  call i32 (ptr, ...) @printf(ptr @.fmt_int_nl, i32 %t3)
  ret i32 0
}
