; Generated by DelphiLLVMGenerator
declare i32 @printf(ptr, ...)
declare i32 @scanf(ptr, ...)

@.fmt_int_nl = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmt_str_nl = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt_read_i = private unnamed_addr constant [3 x i8] c"%d\00"

@i = global i32 0
@sum = global i32 0

define i32 @main() {
entry:
  store i32 0, ptr @i
  store i32 0, ptr @sum
  br label %while_cond_0
while_cond_0:
  %t0 = load i32, ptr @i
  %t1 = icmp slt i32 %t0, 10
  %t2 = zext i1 %t1 to i32
  %t3 = icmp ne i32 %t2, 0
  br i1 %t3, label %while_body_1, label %while_end_2
while_body_1:
  %t4 = load i32, ptr @i
  %t5 = add i32 %t4, 1
  store i32 %t5, ptr @i
  %t6 = load i32, ptr @i
  %t7 = icmp eq i32 %t6, 3
  %t8 = zext i1 %t7 to i32
  %t9 = icmp ne i32 %t8, 0
  br i1 %t9, label %if_then_3, label %if_end_5
if_then_3:
  br label %while_cond_0
if_end_5:
  %t10 = load i32, ptr @i
  %t11 = icmp eq i32 %t10, 8
  %t12 = zext i1 %t11 to i32
  %t13 = icmp ne i32 %t12, 0
  br i1 %t13, label %if_then_6, label %if_end_8
if_then_6:
  br label %while_end_2
if_end_8:
  %t14 = load i32, ptr @sum
  %t15 = load i32, ptr @i
  %t16 = add i32 %t14, %t15
  store i32 %t16, ptr @sum
  br label %while_cond_0
while_end_2:
  %t17 = load i32, ptr @sum
  call i32 (ptr, ...) @printf(ptr @.fmt_int_nl, i32 %t17)
  ret i32 0
}
