package org.example;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Generates LLVM IR (text) from the ANTLR parse tree.
 *
 * Scope in this generator is intentionally focused on the core project-3 path:
 * global vars, routines/functions, arithmetic/relational expressions,
 * if/while/for, break/continue, ReadInt and WriteLn.
 */
public class DelphiLLVMGenerator extends DelphiBaseVisitor<DelphiLLVMGenerator.Value> {
    private static final class RoutineSignature {
        final String name;
        final boolean isFunction;
        final List<String> paramNames;

        RoutineSignature(String name, boolean isFunction, List<String> paramNames) {
            this.name = name;
            this.isFunction = isFunction;
            this.paramNames = paramNames;
        }
    }

    static final class Value {
        final String intOperand;
        final String stringPtr;

        private Value(String intOperand, String stringPtr) {
            this.intOperand = intOperand;
            this.stringPtr = stringPtr;
        }

        static Value intVal(String operand) {
            return new Value(operand, null);
        }

        static Value strVal(String ptrOperand) {
            return new Value(null, ptrOperand);
        }

        boolean isInt() {
            return intOperand != null;
        }

        boolean isString() {
            return stringPtr != null;
        }
    }

    private static final class LoopContext {
        final String breakLabel;
        final String continueLabel;

        LoopContext(String breakLabel, String continueLabel) {
            this.breakLabel = breakLabel;
            this.continueLabel = continueLabel;
        }
    }

    private final StringBuilder header = new StringBuilder();
    private final StringBuilder globals = new StringBuilder();
    private final StringBuilder functions = new StringBuilder();

    private final Map<String, String> globalVars = new HashMap<>();
    private final Map<String, RoutineSignature> routines = new HashMap<>();

    private final Deque<Map<String, String>> localScopes = new ArrayDeque<>();
    private final Deque<LoopContext> loopStack = new ArrayDeque<>();

    private final List<String> currentFunctionBody = new ArrayList<>();

    private int tempCounter = 0;
    private int labelCounter = 0;
    private int stringCounter = 0;

    private boolean blockTerminated = false;
    private String currentRoutineName = null;

    public String generate(DelphiParser.ProgramContext program) {
        emitModulePreamble();

        collectRoutineSignatures(program);
        emitGlobalVars(program);
        emitRoutines(program);
        emitMain(program);

        StringBuilder out = new StringBuilder();
        out.append(header);
        out.append(globals);
        out.append(functions);
        return out.toString();
    }

    private void emitModulePreamble() {
        header.append("; Generated by DelphiLLVMGenerator\n");
        header.append("declare i32 @printf(ptr, ...)\n");
        header.append("declare i32 @scanf(ptr, ...)\n\n");

        globals.append("@.fmt_int_nl = private unnamed_addr constant [4 x i8] c\"%d\\0A\\00\"\n");
        globals.append("@.fmt_str_nl = private unnamed_addr constant [4 x i8] c\"%s\\0A\\00\"\n");
        globals.append("@.fmt_read_i = private unnamed_addr constant [3 x i8] c\"%d\\00\"\n\n");
    }

    private void collectRoutineSignatures(DelphiParser.ProgramContext program) {
        if (program.implementationSection() == null) {
            return;
        }

        for (DelphiParser.RoutineImplementationContext routine : program.implementationSection().routineImplementation()) {
            String name = routine.identifier().getText().toLowerCase(Locale.ROOT);
            boolean isFunction = routine.FUNCTION() != null;
            List<String> params = new ArrayList<>();
            if (routine.formalParameters() != null) {
                for (DelphiParser.ParameterGroupContext group : routine.formalParameters().parameterGroup()) {
                    for (DelphiParser.IdentifierContext id : group.identifierList().identifier()) {
                        params.add(id.getText().toLowerCase(Locale.ROOT));
                    }
                }
            }
            routines.put(name, new RoutineSignature(name, isFunction, params));
        }
    }

    private void emitGlobalVars(DelphiParser.ProgramContext program) {
        if (program.varSection() == null) {
            return;
        }

        for (DelphiParser.VariableDeclarationContext decl : program.varSection().variableDeclaration()) {
            for (DelphiParser.IdentifierContext id : decl.identifierList().identifier()) {
                String name = id.getText().toLowerCase(Locale.ROOT);
                String ptr = "@" + sanitize(name);
                if (!globalVars.containsKey(name)) {
                    globalVars.put(name, ptr);
                    globals.append(ptr).append(" = global i32 0\n");
                }
            }
        }
        globals.append('\n');
    }

    private void emitRoutines(DelphiParser.ProgramContext program) {
        if (program.implementationSection() == null) {
            return;
        }

        for (DelphiParser.RoutineImplementationContext routine : program.implementationSection().routineImplementation()) {
            emitRoutine(routine);
        }
    }

    private void emitRoutine(DelphiParser.RoutineImplementationContext routine) {
        String name = routine.identifier().getText().toLowerCase(Locale.ROOT);
        RoutineSignature sig = routines.get(name);
        if (sig == null) {
            return;
        }

        currentRoutineName = name;
        currentFunctionBody.clear();
        localScopes.clear();
        loopStack.clear();
        blockTerminated = false;
        enterScope();

        StringBuilder signature = new StringBuilder();
        signature.append(sig.isFunction ? "define i32 @" : "define void @");
        signature.append(sanitize(name)).append('(');
        for (int i = 0; i < sig.paramNames.size(); i++) {
            if (i > 0) signature.append(", ");
            signature.append("i32 %arg").append(i);
        }
        signature.append(") {\n");
        functions.append(signature);

        emitLine("entry:");
        tempCounter = 0;

        // Materialize parameters as allocas.
        for (int i = 0; i < sig.paramNames.size(); i++) {
            String pName = sig.paramNames.get(i);
            String ptr = newTemp();
            emitLine("  " + ptr + " = alloca i32");
            emitLine("  store i32 %arg" + i + ", ptr " + ptr);
            defineLocal(pName, ptr);
        }

        if (sig.isFunction) {
            String retPtr = newTemp();
            emitLine("  " + retPtr + " = alloca i32");
            emitLine("  store i32 0, ptr " + retPtr);
            defineLocal(name, retPtr);
        }

        if (routine.varSection() != null) {
            visit(routine.varSection());
        }

        visit(routine.compoundStatement());

        if (!blockTerminated) {
            if (sig.isFunction) {
                String retPtr = resolveVarPtr(name);
                String retVal = emitLoadInt(retPtr);
                emitLine("  ret i32 " + retVal);
            } else {
                emitLine("  ret void");
            }
            blockTerminated = true;
        }

        for (String line : currentFunctionBody) {
            functions.append(line).append('\n');
        }
        functions.append("}\n\n");

        currentRoutineName = null;
        leaveScope();
    }

    private void emitMain(DelphiParser.ProgramContext program) {
        currentRoutineName = "main";
        currentFunctionBody.clear();
        localScopes.clear();
        loopStack.clear();
        blockTerminated = false;
        enterScope();

        functions.append("define i32 @main() {\n");
        emitLine("entry:");
        tempCounter = 0;

        if (program.compoundStatement() != null) {
            visit(program.compoundStatement());
        }

        if (!blockTerminated) {
            emitLine("  ret i32 0");
            blockTerminated = true;
        }

        for (String line : currentFunctionBody) {
            functions.append(line).append('\n');
        }
        functions.append("}\n");

        leaveScope();
        currentRoutineName = null;
    }

    @Override
    public Value visitVarSection(DelphiParser.VarSectionContext ctx) {
        for (DelphiParser.VariableDeclarationContext decl : ctx.variableDeclaration()) {
            visit(decl);
        }
        return null;
    }

    @Override
    public Value visitVariableDeclaration(DelphiParser.VariableDeclarationContext ctx) {
        for (DelphiParser.IdentifierContext id : ctx.identifierList().identifier()) {
            String name = id.getText().toLowerCase(Locale.ROOT);
            if (resolveLocalVarPtr(name) != null) {
                continue;
            }
            String ptr = newTemp();
            emitLine("  " + ptr + " = alloca i32");
            emitLine("  store i32 0, ptr " + ptr);
            defineLocal(name, ptr);
        }
        return null;
    }

    @Override
    public Value visitCompoundStatement(DelphiParser.CompoundStatementContext ctx) {
        enterScope();
        try {
            if (ctx.statementList() != null) {
                visit(ctx.statementList());
            }
        } finally {
            leaveScope();
        }
        return null;
    }

    @Override
    public Value visitStatementList(DelphiParser.StatementListContext ctx) {
        for (DelphiParser.NonEmptyStatementContext stmt : ctx.nonEmptyStatement()) {
            if (blockTerminated) {
                break;
            }
            visit(stmt);
        }
        return null;
    }

    @Override
    public Value visitAssignment(DelphiParser.AssignmentContext ctx) {
        String lhs = ctx.qualifiedIdentifier().getText().toLowerCase(Locale.ROOT);
        if (lhs.contains(".")) {
            throw new UnsupportedOperationException("Object field assignment is not supported in LLVM mode: " + lhs);
        }

        String ptr = resolveVarPtr(lhs);
        if (ptr == null) {
            throw new IllegalStateException("Unknown variable: " + lhs);
        }

        Value v = visit(ctx.expression());
        if (v == null || !v.isInt()) {
            throw new IllegalStateException("Assignment requires integer expression");
        }

        emitLine("  store i32 " + v.intOperand + ", ptr " + ptr);
        return v;
    }

    @Override
    public Value visitMethodCall(DelphiParser.MethodCallContext ctx) {
        String name = ctx.qualifiedIdentifier().getText().toLowerCase(Locale.ROOT);

        if ("writeln".equals(name)) {
            emitWriteLn(ctx.expressionList());
            return null;
        }

        if ("readint".equals(name)) {
            return emitReadInt();
        }

        if (name.contains(".")) {
            throw new UnsupportedOperationException("Object method call is not supported in LLVM mode: " + name);
        }

        RoutineSignature sig = routines.get(name);
        if (sig == null) {
            String ptr = resolveVarPtr(name);
            if (ptr != null) {
                return Value.intVal(emitLoadInt(ptr));
            }
            throw new IllegalStateException("Unknown call target: " + name);
        }

        List<String> args = new ArrayList<>();
        if (ctx.expressionList() != null) {
            for (DelphiParser.ExpressionContext argExpr : ctx.expressionList().expression()) {
                Value arg = visit(argExpr);
                if (arg == null || !arg.isInt()) {
                    throw new IllegalStateException("Routine call only supports integer args");
                }
                args.add("i32 " + arg.intOperand);
            }
        }

        StringBuilder call = new StringBuilder();
        if (sig.isFunction) {
            String r = newTemp();
            call.append("  ").append(r).append(" = call i32 @").append(sanitize(name)).append('(');
            for (int i = 0; i < args.size(); i++) {
                if (i > 0) call.append(", ");
                call.append(args.get(i));
            }
            call.append(')');
            emitLine(call.toString());
            return Value.intVal(r);
        }

        call.append("  call void @").append(sanitize(name)).append('(');
        for (int i = 0; i < args.size(); i++) {
            if (i > 0) call.append(", ");
            call.append(args.get(i));
        }
        call.append(')');
        emitLine(call.toString());
        return null;
    }

    @Override
    public Value visitIfStatement(DelphiParser.IfStatementContext ctx) {
        if (blockTerminated) {
            return null;
        }

        Value condValue = visit(ctx.expression());
        String condI1 = emitIntToI1(condValue.intOperand);

        String thenLabel = newLabel("if_then");
        String elseLabel = newLabel("if_else");
        String endLabel = newLabel("if_end");

        if (ctx.ELSE() != null) {
            emitLine("  br i1 " + condI1 + ", label %" + thenLabel + ", label %" + elseLabel);
        } else {
            emitLine("  br i1 " + condI1 + ", label %" + thenLabel + ", label %" + endLabel);
        }
        blockTerminated = true;

        emitLine(thenLabel + ":");
        blockTerminated = false;
        visit(ctx.nonEmptyStatement(0));
        boolean thenTerminated = blockTerminated;
        if (!thenTerminated) {
            emitLine("  br label %" + endLabel);
        }

        boolean elseTerminated = false;
        if (ctx.ELSE() != null) {
            emitLine(elseLabel + ":");
            blockTerminated = false;
            visit(ctx.nonEmptyStatement(1));
            elseTerminated = blockTerminated;
            if (!elseTerminated) {
                emitLine("  br label %" + endLabel);
            }
        }

        emitLine(endLabel + ":");
        blockTerminated = false;
        if (ctx.ELSE() != null && thenTerminated && elseTerminated) {
            // Keep flow alive for codegen simplicity even if logically unreachable.
            blockTerminated = false;
        }

        return null;
    }

    @Override
    public Value visitWhileStatement(DelphiParser.WhileStatementContext ctx) {
        if (blockTerminated) {
            return null;
        }

        String condLabel = newLabel("while_cond");
        String bodyLabel = newLabel("while_body");
        String endLabel = newLabel("while_end");

        emitLine("  br label %" + condLabel);
        emitLine(condLabel + ":");
        blockTerminated = false;

        Value cond = visit(ctx.expression());
        String condI1 = emitIntToI1(cond.intOperand);
        emitLine("  br i1 " + condI1 + ", label %" + bodyLabel + ", label %" + endLabel);

        emitLine(bodyLabel + ":");
        blockTerminated = false;
        loopStack.push(new LoopContext(endLabel, condLabel));
        visit(ctx.nonEmptyStatement());
        loopStack.pop();
        if (!blockTerminated) {
            emitLine("  br label %" + condLabel);
        }

        emitLine(endLabel + ":");
        blockTerminated = false;
        return null;
    }

    @Override
    public Value visitForStatement(DelphiParser.ForStatementContext ctx) {
        if (blockTerminated) {
            return null;
        }

        String varName = ctx.identifier().getText().toLowerCase(Locale.ROOT);
        String varPtr = resolveVarPtr(varName);
        if (varPtr == null) {
            throw new IllegalStateException("For loop variable not found: " + varName);
        }

        Value start = visit(ctx.expression(0));
        Value end = visit(ctx.expression(1));
        boolean downTo = ctx.DOWNTO() != null;

        emitLine("  store i32 " + start.intOperand + ", ptr " + varPtr);

        String condLabel = newLabel("for_cond");
        String bodyLabel = newLabel("for_body");
        String stepLabel = newLabel("for_step");
        String endLabel = newLabel("for_end");

        emitLine("  br label %" + condLabel);

        emitLine(condLabel + ":");
        blockTerminated = false;
        String cur = emitLoadInt(varPtr);
        String cmp = newTemp();
        if (downTo) {
            emitLine("  " + cmp + " = icmp sge i32 " + cur + ", " + end.intOperand);
        } else {
            emitLine("  " + cmp + " = icmp sle i32 " + cur + ", " + end.intOperand);
        }
        emitLine("  br i1 " + cmp + ", label %" + bodyLabel + ", label %" + endLabel);

        emitLine(bodyLabel + ":");
        blockTerminated = false;
        loopStack.push(new LoopContext(endLabel, stepLabel));
        visit(ctx.nonEmptyStatement());
        loopStack.pop();
        if (!blockTerminated) {
            emitLine("  br label %" + stepLabel);
        }

        emitLine(stepLabel + ":");
        blockTerminated = false;
        String oldV = emitLoadInt(varPtr);
        String nextV = newTemp();
        if (downTo) {
            emitLine("  " + nextV + " = sub i32 " + oldV + ", 1");
        } else {
            emitLine("  " + nextV + " = add i32 " + oldV + ", 1");
        }
        emitLine("  store i32 " + nextV + ", ptr " + varPtr);
        emitLine("  br label %" + condLabel);

        emitLine(endLabel + ":");
        blockTerminated = false;
        return null;
    }

    @Override
    public Value visitBreakStatement(DelphiParser.BreakStatementContext ctx) {
        if (loopStack.isEmpty()) {
            throw new IllegalStateException("break used outside loop");
        }
        emitLine("  br label %" + loopStack.peek().breakLabel);
        blockTerminated = true;
        return null;
    }

    @Override
    public Value visitContinueStatement(DelphiParser.ContinueStatementContext ctx) {
        if (loopStack.isEmpty()) {
            throw new IllegalStateException("continue used outside loop");
        }
        emitLine("  br label %" + loopStack.peek().continueLabel);
        blockTerminated = true;
        return null;
    }

    @Override
    public Value visitExpression(DelphiParser.ExpressionContext ctx) {
        Value left = visit(ctx.relExpression(0));
        for (int i = 1; i < ctx.relExpression().size(); i++) {
            String op = ctx.getChild(2 * i - 1).getText().toLowerCase(Locale.ROOT);
            Value right = visit(ctx.relExpression(i));

            String l1 = emitIntToI1(left.intOperand);
            String r1 = emitIntToI1(right.intOperand);
            String logic = newTemp();
            if ("and".equals(op)) {
                emitLine("  " + logic + " = and i1 " + l1 + ", " + r1);
            } else {
                emitLine("  " + logic + " = or i1 " + l1 + ", " + r1);
            }
            left = Value.intVal(emitBoolToInt(logic));
        }
        return left;
    }

    @Override
    public Value visitRelExpression(DelphiParser.RelExpressionContext ctx) {
        Value left = visit(ctx.additiveExpression(0));
        if (ctx.additiveExpression().size() == 1) {
            return left;
        }

        Value right = visit(ctx.additiveExpression(1));
        String cmp = newTemp();

        if (ctx.GT() != null) {
            emitLine("  " + cmp + " = icmp sgt i32 " + left.intOperand + ", " + right.intOperand);
        } else if (ctx.LT() != null) {
            emitLine("  " + cmp + " = icmp slt i32 " + left.intOperand + ", " + right.intOperand);
        } else if (ctx.EQUAL() != null) {
            emitLine("  " + cmp + " = icmp eq i32 " + left.intOperand + ", " + right.intOperand);
        } else if (ctx.LE() != null) {
            emitLine("  " + cmp + " = icmp sle i32 " + left.intOperand + ", " + right.intOperand);
        } else if (ctx.GE() != null) {
            emitLine("  " + cmp + " = icmp sge i32 " + left.intOperand + ", " + right.intOperand);
        } else {
            emitLine("  " + cmp + " = icmp ne i32 " + left.intOperand + ", " + right.intOperand);
        }

        return Value.intVal(emitBoolToInt(cmp));
    }

    @Override
    public Value visitAdditiveExpression(DelphiParser.AdditiveExpressionContext ctx) {
        Value acc = visit(ctx.term(0));
        for (int i = 1; i < ctx.term().size(); i++) {
            String op = ctx.getChild(2 * i - 1).getText();
            Value rhs = visit(ctx.term(i));
            String t = newTemp();
            if ("+".equals(op)) {
                emitLine("  " + t + " = add i32 " + acc.intOperand + ", " + rhs.intOperand);
            } else {
                emitLine("  " + t + " = sub i32 " + acc.intOperand + ", " + rhs.intOperand);
            }
            acc = Value.intVal(t);
        }
        return acc;
    }

    @Override
    public Value visitTerm(DelphiParser.TermContext ctx) {
        Value acc = visit(ctx.factor(0));
        for (int i = 1; i < ctx.factor().size(); i++) {
            String op = ctx.getChild(2 * i - 1).getText();
            Value rhs = visit(ctx.factor(i));
            String t = newTemp();
            if ("*".equals(op)) {
                emitLine("  " + t + " = mul i32 " + acc.intOperand + ", " + rhs.intOperand);
            } else {
                emitLine("  " + t + " = sdiv i32 " + acc.intOperand + ", " + rhs.intOperand);
            }
            acc = Value.intVal(t);
        }
        return acc;
    }

    @Override
    public Value visitFactor(DelphiParser.FactorContext ctx) {
        if (ctx.INT_LITERAL() != null) {
            return Value.intVal(ctx.INT_LITERAL().getText());
        }

        if (ctx.STRING_LITERAL() != null) {
            String raw = ctx.STRING_LITERAL().getText();
            String content = unquotePascalString(raw);
            return Value.strVal(emitStringPtr(content));
        }

        if (ctx.methodCall() != null) {
            Value v = visit(ctx.methodCall());
            return v == null ? Value.intVal("0") : v;
        }

        if (ctx.qualifiedIdentifier() != null) {
            String name = ctx.qualifiedIdentifier().getText().toLowerCase(Locale.ROOT);
            if (name.contains(".")) {
                throw new UnsupportedOperationException("Object access is not supported in LLVM mode: " + name);
            }
            String ptr = resolveVarPtr(name);
            if (ptr == null) {
                throw new IllegalStateException("Unknown identifier: " + name);
            }
            return Value.intVal(emitLoadInt(ptr));
        }

        return visit(ctx.expression());
    }

    private void emitWriteLn(DelphiParser.ExpressionListContext args) {
        if (args == null || args.expression().isEmpty()) {
            String empty = emitStringPtr("");
            emitLine("  call i32 (ptr, ...) @printf(ptr @.fmt_str_nl, ptr " + empty + ")");
            return;
        }

        for (DelphiParser.ExpressionContext expr : args.expression()) {
            Value val = visit(expr);
            if (val.isString()) {
                emitLine("  call i32 (ptr, ...) @printf(ptr @.fmt_str_nl, ptr " + val.stringPtr + ")");
            } else {
                emitLine("  call i32 (ptr, ...) @printf(ptr @.fmt_int_nl, i32 " + val.intOperand + ")");
            }
        }
    }

    private Value emitReadInt() {
        String ptr = newTemp();
        emitLine("  " + ptr + " = alloca i32");
        emitLine("  call i32 (ptr, ...) @scanf(ptr @.fmt_read_i, ptr " + ptr + ")");
        return Value.intVal(emitLoadInt(ptr));
    }

    private String emitStringPtr(String content) {
        String globalName = "@.str." + (stringCounter++);
        String escaped = escapeCString(content);
        int len = byteLen(escaped) + 1;

        globals.append(globalName)
                .append(" = private unnamed_addr constant [")
                .append(len)
                .append(" x i8] c\"")
                .append(escaped)
                .append("\\00\"\n");

        String gep = newTemp();
        emitLine("  " + gep + " = getelementptr inbounds [" + len + " x i8], ptr " + globalName + ", i64 0, i64 0");
        return gep;
    }

    private String emitLoadInt(String ptr) {
        String t = newTemp();
        emitLine("  " + t + " = load i32, ptr " + ptr);
        return t;
    }

    private String emitIntToI1(String intOperand) {
        String t = newTemp();
        emitLine("  " + t + " = icmp ne i32 " + intOperand + ", 0");
        return t;
    }

    private String emitBoolToInt(String i1) {
        String t = newTemp();
        emitLine("  " + t + " = zext i1 " + i1 + " to i32");
        return t;
    }

    private void emitLine(String line) {
        currentFunctionBody.add(line);
    }

    private String newTemp() {
        return "%t" + (tempCounter++);
    }

    private String newLabel(String prefix) {
        return prefix + "_" + (labelCounter++);
    }

    private void enterScope() {
        localScopes.push(new HashMap<>());
    }

    private void leaveScope() {
        localScopes.pop();
    }

    private void defineLocal(String name, String ptr) {
        localScopes.peek().put(name.toLowerCase(Locale.ROOT), ptr);
    }

    private String resolveLocalVarPtr(String name) {
        String key = name.toLowerCase(Locale.ROOT);
        for (Map<String, String> scope : localScopes) {
            if (scope.containsKey(key)) {
                return scope.get(key);
            }
        }
        return null;
    }

    private String resolveVarPtr(String name) {
        String local = resolveLocalVarPtr(name);
        if (local != null) {
            return local;
        }
        return globalVars.get(name.toLowerCase(Locale.ROOT));
    }

    private static String sanitize(String name) {
        return name.replace('.', '_');
    }

    private static String unquotePascalString(String raw) {
        if (raw == null || raw.length() < 2) {
            return "";
        }
        return raw.substring(1, raw.length() - 1).replace("''", "'");
    }

    private static String escapeCString(String s) {
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '\\') out.append("\\5C");
            else if (c == '\n') out.append("\\0A");
            else if (c == '\r') out.append("\\0D");
            else if (c == '"') out.append("\\22");
            else if (c < 32 || c > 126) out.append(String.format("\\%02X", (int) c));
            else out.append(c);
        }
        return out.toString();
    }

    private static int byteLen(String llvmEscaped) {
        int count = 0;
        for (int i = 0; i < llvmEscaped.length(); i++) {
            char c = llvmEscaped.charAt(i);
            if (c == '\\' && i + 2 < llvmEscaped.length()) {
                i += 2;
            }
            count++;
        }
        return count;
    }
}
